<a href="https://colab.research.google.com/github/dhanushch18/Inroduction-to-Numpy/blob/main/Numpy002_Maths%26Satistical_Func.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
arr=np.array([[4,5,6],[1,2,3],[6,9,1]])

In [7]:
arr

array([[4, 5, 6],
       [1, 2, 3],
       [6, 9, 1]])

In [4]:
np.amin(arr)

1

In [8]:
np.amin(arr,axis=0) #0=vertical

array([1, 2, 1])

In [9]:
np.amax(arr)

9

In [10]:
np.mean(arr)

4.111111111111111

In [11]:
np.std(arr)

2.5141574442188355

In [12]:
np.var(arr)

6.320987654320987

In [19]:
deg=np.array([0,30,45,60,90])


In [20]:
np.sin(deg*np.pi/180)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [21]:
np.cos(deg*np.pi/180)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [22]:
np.floor(arr)

array([[4., 5., 6.],
       [1., 2., 3.],
       [6., 9., 1.]])